aiofiles>=0.5.0
aiohttp>=3.8.3
boto3>=1.17.74
celery>=5.2.7
# TODO: Remove this when the fix is available in non beta
# We have to use a beta version of kombu on Python 3.7
# because only that fixes "AttributeError: 'EntryPoints' object has no attribute 'get'"
# that we have in the CI: https://app.circleci.com/pipelines/github/instana/python-sensor/1372/workflows/90878561-aada-49f8-8a1b-78562aa05aab/jobs/7478
# the issue: https://github.com/celery/kombu/issues/1600
# the PR: https://github.com/celery/kombu/pull/1601/files
# the release notes: https://github.com/celery/kombu/releases/tag/v5.3.0b2
kombu>=5.3.0b2

coverage>=5.5
Django>=3.2.10
fastapi>=0.92.0
flask>=2.2.3
grpcio>=1.37.1
google-cloud-pubsub<=2.1.0
google-cloud-storage>=1.24.0
lxml>=4.9.2
mock>=4.0.3
moto>=4.1.2
mysqlclient>=2.0.3
nose>=1.3.7
PyMySQL[rsa]>=1.0.2
psycopg2-binary>=2.8.6
pika>=1.2.0

# protobuf is pulled in and also `basictracer`, a core instana dependency
# and also by google-cloud-storage
# but also directly needed by tests/apps/grpc_server/stan_pb2.py
# On 4.0.0 we currently get:
# AttributeError: module 'google._upb._message' has no attribute 'Message'
# TODO: Remove this when support for 4.0.0 is done
protobuf<4.0.0

pymongo>=3.11.4
pyramid>=2.0.1
pytest>=6.2.4
pytest-celery
redis>=3.5.3
requests-mock
responses<=0.17.0
sanic==21.6.2
sqlalchemy>=2.0.0
spyne>=2.14.0
tornado>=4.5.3,<6.0
uvicorn>=0.13.4
urllib3[secure]<1.27,>=1.26.5
